<?php

require_once dirname(__FILE__) . '/../twigpress.php';

/**
 * Test class for foo.
 * Generated by PHPUnit on 2012-03-20 at 21:24:59.
 */
class twigpressTest extends PHPUnit_Framework_TestCase {

    /**
     * @var foo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
       $this->object = new Twigpress();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Twigpress::__construct
     */
    public function testConstruct() {
        // Assert that twigpress will look for missing templates
        $paths = $this->object->getLoader()->getPaths();
        $this->assertEquals($paths[0], PROJECT_ROOT);
        
    }
  
      
    /**
     * @covers Twigpress::__addPath
     */
    public function testAppendPath() {
        
        $this->object->appendPath(MOCKUPS_DIR);
        $paths = $this->object->getLoader()->getPaths();
        $this->assertContains(MOCKUPS_DIR, $paths);
    }
    
    /**
     * @covers Twigpress::__addPath
     */
    public function testPrependPath() {
        $this->object->prependPath(MOCKUPS_DIR);
        $paths = $this->object->getLoader()->getPaths();
        $this->assertContains(MOCKUPS_DIR, $paths);
        $this->assertEquals($paths[0], MOCKUPS_DIR);
    }
}

?>
