<?php
/**
 * Test class for Twigpress_Environment.
 * Generated by PHPUnit on 2012-03-21 at 22:54:56.
 */
class Twigpress_EnvironmentTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Twigpress_Environment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Twigpress_Environment;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    /**
     * @covers Twigpress_Environment::autoDisplay
     */
    public function testAutoRender() {
      //  $output = $this->object->autoRender(new Wp_Query_stub);
      //  $this->assertContains('html', $output);
      //  $this->assertContains('<title>Twigpress: Autodisplay Error</title>', $output);
      $output = $this->object->autoRender(new Wp_Query_stub);  
      $this->assertFalse($output);
    }

    /**
     * @covers Twigpress_Environment::init
     * @todo Implement testInit().
     */
    public function testInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
