<?php

require_once dirname(__FILE__) . '/../../lib/template_loader.php';
require_once PROJECT_ROOT . '/twigpress.php';
/**
 * Test class for Twigpress_Template_Loader.
 * Generated by PHPUnit on 2012-03-21 at 00:46:54.
 */
class Twigpress_Template_LoaderTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Twigpress_Template_Loader
     */
    protected $object;
    protected $env; 
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->env = new Twigpress();
        $this->object = new Twigpress_Template_Loader($this->env->getLoader());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGet_template().
     */
    public function testGet_template() {
        // Remove the following lines when you implement this test.

        $this->assertAttributeEquals($this->env->getLoader(), 'loader', $this->object);
        
        $query = new TP_Query();
        $query->type = 'foo';
  
        
        $this->env->prependPath(PROJECT_ROOT.'/tests/mockups/themes/TwigpressTestTheme/');
       
        $this->assertEquals('index.html.twig', $this->object->get_template($query));
        
        $this->env->prependPath(PROJECT_ROOT.'/tests/mockups/themes/TwigpressTestTheme2/');
        
        $this->assertEquals('foo.html.twig', $this->object->get_template($query));
        
    }
    
    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGet_template().
     */
    public function testGet_template2() {
        // Remove the following lines when you implement this test.

        $this->assertAttributeEquals($this->env->getLoader(), 'loader', $this->object);
        
        $query = new TP_Query();
        $query->type = 'foo';
  
        $this->env->getLoader()->setPaths(array());
        $this->env->prependPath(PROJECT_ROOT.'/tests/mockups/themes/TwigpressBareTestTheme/');
        
        
        $this->assertEquals('index.html.twig', $this->object->get_template($query));

        
    }

}