<?php

/**
 * Test class for foo.
 * Generated by PHPUnit on 2012-03-20 at 21:24:59.
 */
class loopTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Twigpress
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
       $this->object = new Twigpress_Environment();
        $this->object->appendPath(__DIR__);
       $this->object->addTokenParser(new Twigpress_TokenParser_Loop());
       
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testLoopActsAsFor(){
        
        $template = $this->object->loadTemplate('loopTest.twig')->render(array(
           'data' => array(1, 2, 3) 
        ));
        $this->assertContains('123', $template);
    }
}